version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Clone only the docs submodule into A/docs (recursively if it has its own)
submodules:
  include:
    - doc
  recursive: true

sphinx:
  # Path to conf.py relative to A/
  configuration: doc/source/conf.py
  # (optional) choose builder
  # builder: html

python:
  install:
    # If your Sphinx deps live inside the submodule:
    - requirements: doc/requirements.txt
    # If you also need to install A as a package for autodoc:
    # - method: pip
    #   path: .
