"""
Tests for the entity naming system.

Covers: auto-naming, user-naming, duplicates, lookups, solver prefixes.
"""

import platform
from unittest.mock import patch

import pytest

import genesis as gs

# Check for USD support
try:
    from pxr import Usd, UsdGeom, UsdPhysics

    HAS_USD_SUPPORT = True
except ImportError:
    HAS_USD_SUPPORT = False


# =============================================================================
# Fixtures
# =============================================================================


@pytest.fixture
def scene():
    """Create a basic scene and destroy it after the test."""
    s = gs.Scene(show_viewer=False)
    yield s
    s.destroy()


def make_drone_urdf(tmp_path, name="test_drone"):
    """Create a minimal Drone URDF with required properties and prop links."""
    content = f"""<?xml version="1.0"?>
<robot name="{name}">
  <properties kf="3.16e-10" km="7.94e-12" />
  <link name="base_link">
    <inertial><mass value="0.5"/><inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/></inertial>
  </link>
  {
        "".join(
            f'''
  <link name="prop{i}_link"><inertial><mass value="0.01"/><inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/></inertial></link>
  <joint name="prop{i}_joint" type="fixed"><parent link="base_link"/><child link="prop{i}_link"/></joint>'''
            for i in range(4)
        )
    }
</robot>"""
    path = tmp_path / f"{name}.urdf"
    path.write_text(content)
    return path


# =============================================================================
# Core Naming Tests
# =============================================================================


class TestAutoGeneratedNames:
    """Tests for auto-generated entity names."""

    @pytest.mark.parametrize(
        "morph_factory,prefix",
        [
            (lambda: gs.morphs.Box(size=(0.1, 0.1, 0.1)), "box_"),
            (lambda: gs.morphs.Sphere(radius=0.1), "sphere_"),
            (lambda: gs.morphs.Cylinder(radius=0.1, height=0.2), "cylinder_"),
            (lambda: gs.morphs.Plane(), "plane_"),
        ],
        ids=["box", "sphere", "cylinder", "plane"],
    )
    def test_primitive_auto_names(self, scene, morph_factory, prefix):
        """Test auto-generated names for primitive morphs."""
        entity = scene.add_entity(morph_factory())
        assert entity.name.startswith(prefix)
        assert len(entity.name) == len(prefix) + 8  # 8-char UID suffix

    def test_unique_names_for_same_type(self, scene):
        """Test that multiple entities of same type get unique names."""
        box1 = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
        box2 = scene.add_entity(gs.morphs.Box(size=(0.2, 0.2, 0.2)))
        assert box1.name != box2.name

    def test_heterogeneous_auto_name(self, scene):
        """Test auto-generated name for heterogeneous entities."""
        entity = scene.add_entity([gs.morphs.Box(size=(0.1, 0.1, 0.1)), gs.morphs.Sphere(radius=0.1)])
        assert entity.name.startswith("heterogeneous_")


class TestUserSpecifiedNames:
    """Tests for user-specified entity names."""

    def test_user_specified_name(self, scene):
        """Test that user-specified names are used correctly."""
        box = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="my_box")
        assert box.name == "my_box"

    def test_duplicate_name_raises_error(self, scene):
        """Test that duplicate names raise an exception."""
        scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="duplicate")
        with pytest.raises(Exception, match="already exists"):
            scene.add_entity(gs.morphs.Sphere(radius=0.1), name="duplicate")


class TestSceneGetEntity:
    """Tests for Scene.get_entity() method."""

    def test_get_entity_by_name(self, scene):
        """Test retrieving entity by name."""
        box = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="test_box")
        assert scene.get_entity(name="test_box") is box

    def test_get_entity_by_uid_prefix(self, scene):
        """Test retrieving entity by UID prefix."""
        box = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
        uid_prefix = str(box.uid)[:4]
        assert scene.get_entity(uid=uid_prefix) is box

    @pytest.mark.parametrize("lookup", [{"name": "nonexistent"}, {"uid": "zzzzzzzz"}])
    def test_get_entity_not_found(self, scene, lookup):
        """Test that get_entity raises exception when not found."""
        scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
        with pytest.raises(Exception, match="(?i)not found"):
            scene.get_entity(**lookup)

    def test_get_entity_no_args_raises_error(self, scene):
        """Test that get_entity raises exception when no args provided."""
        scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
        with pytest.raises(Exception, match="(?i)neither"):
            scene.get_entity()


class TestSceneEntityNames:
    """Tests for Scene.entity_names property."""

    def test_entity_names_order(self, scene):
        """Test that entity_names preserves creation order."""
        scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="first")
        scene.add_entity(gs.morphs.Sphere(radius=0.1), name="second")
        scene.add_entity(gs.morphs.Cylinder(radius=0.1, height=0.2), name="third")
        assert scene.entity_names == ["first", "second", "third"]

    def test_entity_names_mixed_auto_user(self, scene):
        """Test entity_names with mix of auto and user names."""
        scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="named")
        scene.add_entity(gs.morphs.Sphere(radius=0.1))
        names = scene.entity_names
        assert names[0] == "named"
        assert names[1].startswith("sphere_")


# =============================================================================
# File-Based Morph Naming
# =============================================================================


class TestFileBasedMorphNaming:
    """Tests for file-based morph naming (Mesh, URDF, MJCF)."""

    @pytest.mark.parametrize(
        "morph_factory,expected_prefix",
        [
            (lambda: gs.morphs.Mesh(file="meshes/bunny.obj"), "bunny_"),
            (lambda: gs.morphs.URDF(file="urdf/go2/urdf/go2.urdf"), "go2_"),
            (lambda: gs.morphs.MJCF(file="xml/ant.xml"), "ant_"),
        ],
        ids=["mesh", "urdf", "mjcf"],
    )
    def test_file_based_auto_name(self, scene, morph_factory, expected_prefix):
        """Test auto-generated name uses file stem."""
        entity = scene.add_entity(morph_factory())
        assert entity.name.startswith(expected_prefix), f"Expected '{expected_prefix}' prefix, got '{entity.name}'"


class TestTerrainNaming:
    """Tests for Terrain entity naming."""

    def test_terrain_with_name_attr(self, scene):
        """Test Terrain with name attribute uses it as prefix."""
        terrain = scene.add_entity(
            gs.morphs.Terrain(name="my_terrain", n_subterrains=(1, 1), subterrain_types="flat_terrain")
        )
        assert terrain.name.startswith("my_terrain_")

    def test_terrain_default_prefix(self, scene):
        """Test Terrain without name uses 'terrain_' prefix."""
        terrain = scene.add_entity(gs.morphs.Terrain(n_subterrains=(1, 1), subterrain_types="flat_terrain"))
        assert terrain.name.startswith("terrain_")


class TestDroneNaming:
    """Tests for Drone entity naming."""

    def test_drone_uses_file_stem(self, scene, tmp_path):
        """Test Drone auto-name uses file stem."""
        urdf_path = make_drone_urdf(tmp_path, "my_quad")
        drone = scene.add_entity(gs.morphs.Drone(file=str(urdf_path)))
        assert drone.name.startswith("my_quad_")
        assert len(drone.name.split("_")[-1]) == 8  # 8-char UID suffix


# =============================================================================
# Solver-Prefixed Names
# =============================================================================


class TestSolverPrefixedNames:
    """Tests for solver-prefixed entity names (FEM, MPM, PBD, SPH, SF)."""

    def test_sf_entity_prefix(self):
        """Test SF entity _generate_name() has 'sf_' prefix."""
        from genesis.engine.entities.sf_entity import SFParticleEntity

        fixed_uid = "sf123456abcdef78"

        class MockUID:
            def __str__(self):
                return fixed_uid

        class MockSFEntity(SFParticleEntity):
            def __init__(self, morph, uid):
                self._morph = morph
                self._uid = uid

        entity = MockSFEntity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), MockUID())
        assert entity._generate_name() == f"sf_box_{fixed_uid[:8]}"

    @pytest.mark.skipif(platform.machine() == "aarch64", reason="tetgen may crash on ARM")
    def test_fem_entity_prefix(self, box_obj_path):
        """Test FEM entity has 'fem_' prefix."""
        scene = gs.Scene(show_viewer=False)
        entity = scene.add_entity(gs.morphs.Mesh(file=box_obj_path), material=gs.materials.FEM.Elastic())
        assert entity.name.startswith("fem_")
        scene.destroy()

    def test_mpm_entity_prefix(self):
        """Test MPM entity has 'mpm_' prefix."""
        scene = gs.Scene(
            sim_options=gs.options.SimOptions(dt=1e-3, substeps=10),
            mpm_options=gs.options.MPMOptions(lower_bound=(-1, -1, 0), upper_bound=(1, 1, 2)),
            show_viewer=False,
        )
        entity = scene.add_entity(
            gs.morphs.Box(pos=(0, 0, 0.5), size=(0.2, 0.2, 0.2)), material=gs.materials.MPM.Elastic()
        )
        assert entity.name.startswith("mpm_box_")
        scene.destroy()

    @pytest.mark.skipif(platform.machine() == "aarch64", reason="tetgen may crash on ARM")
    def test_pbd_entity_prefix(self, box_obj_path):
        """Test PBD entity has 'pbd_' prefix."""
        scene = gs.Scene(pbd_options=gs.options.PBDOptions(particle_size=0.1), show_viewer=False)
        entity = scene.add_entity(gs.morphs.Mesh(file=box_obj_path), material=gs.materials.PBD.Elastic())
        assert entity.name.startswith("pbd_")
        scene.destroy()

    def test_sph_entity_prefix(self):
        """Test SPH entity has 'sph_' prefix."""
        scene = gs.Scene(
            sim_options=gs.options.SimOptions(dt=4e-3, substeps=10),
            sph_options=gs.options.SPHOptions(
                lower_bound=(-0.5, -0.5, 0), upper_bound=(0.5, 0.5, 1), particle_size=0.02
            ),
            show_viewer=False,
        )
        entity = scene.add_entity(
            gs.morphs.Box(pos=(0, 0, 0.5), size=(0.2, 0.2, 0.2)), material=gs.materials.SPH.Liquid(sampler="regular")
        )
        assert entity.name.startswith("sph_box_")
        scene.destroy()


# =============================================================================
# Edge Cases
# =============================================================================


class TestEdgeCases:
    """Tests for edge cases: UID ambiguity, auto-name collision."""

    def test_uid_ambiguous_prefix_raises_error(self, scene):
        """Test that ambiguous UID prefix raises error."""

        class MockUID:
            def __init__(self, value):
                self.uid = value

            def __str__(self):
                return self.uid

        box1 = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="box1")
        box2 = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)), name="box2")
        box1._uid = MockUID("abc11111aaaaaaaa")
        box2._uid = MockUID("abc22222bbbbbbbb")

        with pytest.raises(Exception, match="(?i)multiple"):
            scene.get_entity(uid="abc")

    def test_auto_name_collision_detected(self):
        """Test that auto-generated name collisions are detected."""
        fixed_uid = "deadbeef12345678"

        class MockUID:
            def __init__(self):
                self.uid = fixed_uid

            def __str__(self):
                return self.uid

        with patch("genesis.UID", MockUID):
            scene = gs.Scene(show_viewer=False)
            box1 = scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
            assert box1.name == f"box_{fixed_uid[:8]}"

            with pytest.raises(Exception, match="already exists"):
                scene.add_entity(gs.morphs.Box(size=(0.1, 0.1, 0.1)))
            scene.destroy()


# =============================================================================
# USD Naming Tests
# =============================================================================


@pytest.mark.skipif(not HAS_USD_SUPPORT, reason="USD support not available (requires pxr library)")
class TestUSDNaming:
    """Tests for USD entity naming with add_stage API."""

    @pytest.fixture
    def simple_usd_file(self, tmp_path):
        """Create a minimal USD file for testing."""
        usd_file = tmp_path / "test_model.usda"
        stage = Usd.Stage.CreateNew(str(usd_file))
        UsdGeom.SetStageUpAxis(stage, "Z")
        UsdGeom.SetStageMetersPerUnit(stage, 1.0)

        root = stage.DefinePrim("/World", "Xform")
        stage.SetDefaultPrim(root)

        # Create floor (fixed)
        floor = UsdGeom.Plane.Define(stage, "/World/floor")
        floor.GetAxisAttr().Set("Z")
        UsdPhysics.CollisionAPI.Apply(floor.GetPrim())

        # Create a simple box (free rigid body)
        box = UsdGeom.Cube.Define(stage, "/World/TestBox")
        box.GetSizeAttr().Set(0.2)
        box.AddTranslateOp().Set((0, 0, 0.5))
        rigid_api = UsdPhysics.RigidBodyAPI.Apply(box.GetPrim())
        rigid_api.GetKinematicEnabledAttr().Set(False)

        stage.Save()
        return str(usd_file)

    def test_usd_entities_have_names(self, simple_usd_file):
        """Test USD entities created via add_stage have auto-generated names."""
        scene = gs.Scene(show_viewer=False)
        # add_stage returns a dict of entities keyed by prim path
        entities = scene.add_stage(gs.morphs.USD(file=simple_usd_file), vis_mode="collision")

        # Check that entities were created and have names
        assert len(entities) > 0, "Expected at least one entity from USD stage"

        for prim_path, entity in entities.items():
            assert entity.name is not None, f"Entity at {prim_path} should have a name"
            assert len(entity.name) > 0, f"Entity at {prim_path} should have non-empty name"
            # Verify 8-char UID suffix exists
            parts = entity.name.split("_")
            assert len(parts[-1]) == 8, f"Expected 8-char UID suffix, got '{parts[-1]}' for {prim_path}"

        scene.destroy()
