"""
Upload memory benchmark results to Weights & Biases.

This script parses the memory results file generated by monitor_test_mem.py
and uploads all tests' memory usage to a single W&B run.

To test this use e.g.:

env=franka 	| constraint_solver=None 	| gjk_collision=True 	| batch_size=30000 	| backend=cuda 	| dtype=field 	| max_mem_mb=123
env=franka 	| constraint_solver=None 	| gjk_collision=True 	| batch_size=3000 	| backend=cpu 	| dtype=field 	| max_mem_mb=255

... and check that uploads to
https://wandb.ai/genesis-ai-company/genesis-benchmarks-mem/table
correctly
"""

import argparse
import wandb
import os
import sys
from pathlib import Path

from utils import get_git_commit_info, pprint_oneline


def upload_memory_to_wandb(mem_file_path):
    """
    Parse memory results file in pipe-delimited format and upload to W&B.
    """
    revision, _ = get_git_commit_info()
    print(f"Uploading memory metrics to W&B for revision: {revision}")

    uploaded_count = 0
    skipped_count = 0

    # Initialize a single run for all benchmark results
    run = wandb.init(
        project="genesis-benchmarks-mem",
        name=f"memory-{revision[:12]}",
        config={
            "revision": revision,
        },
        settings=wandb.Settings(
            x_disable_stats=True,
            console="off",
        ),
    )

    with open(mem_file_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # Parse pipe-delimited format: key=value | key=value | ...
            params = {}
            for part in line.split(" \t| "):
                if "=" in part:
                    k, v = part.split("=", 1)
                    params[k.strip()] = v.strip()

            if "max_mem_mb" not in params:
                skipped_count += 1
                continue

            max_mem_mb = float(params.pop("max_mem_mb"))

            # Create benchmark ID matching alarm.yml format
            # Format: memory-env=franka-batch_size=30000-backend=cuda-dtype=field
            benchmark_id = f"memory-{pprint_oneline(params, delimiter='-')}"

            print(f"📊 Uploading {benchmark_id}: {max_mem_mb:.0f} MB")

            # Log each benchmark result with its ID as the metric name
            run.log({benchmark_id: max_mem_mb})

            uploaded_count += 1

    run.finish()

    print(f"\n✅ Memory upload complete: {uploaded_count} uploaded, {skipped_count} skipped")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--in-mem-file", required=True)
    args = parser.parse_args()
    return upload_memory_to_wandb(mem_file_path=args.in_mem_file)


if __name__ == "__main__":
    main()
