FROM rocm/pytorch:rocm7.2.4_ubuntu22.04_py3.10_pytorch_release_2.8.0@sha256:880e126d83370e3502b069a39f85cbd7b1f6f7dbfbceb00b6fefbac03c5da091

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace/examples

# Install Vulkan
RUN wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | tee /etc/apt/trusted.gpg.d/lunarg.asc
RUN wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.4.309-jammy.list https://packages.lunarg.com/vulkan/1.4.309/lunarg-vulkan-1.4.309-jammy.list
RUN apt update
RUN apt install -y vulkan-sdk

# handle add the render group
RUN groupadd -f render
RUN usermod -aG render root
RUN usermod -aG video root

# Necessary for visualisation on Wayland backed systems like Ubuntu
ENV PYOPENGL_PLATFORM='glx'

# Install Genesis with a supported PyTorch release
RUN pip3 install genesis-world trimesh

# Workaround for igl issue
RUN pip3 install libigl==2.5.1 
